[build]
builder = "nixpacks"
buildCommand = "npm install && npm run build"

[deploy]
startCommand = "npm run start"
healthcheckPath = "/api/projects"
restartPolicyType = "on_failure"

[phases.setup]
nixPkgs = ["nodejs", "npm"] 